language: node_js
node_js:
- 8.1.4
install:
- npm install --production
notifications:
  email:
  - sales@sidrilling.co.uk
  - rpprroger@gmail.com
before_script:
- npm run lint
script:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then export NODE_ENV="development"; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then 
    export TRACKING_CODE="UA-96594891-2";
    export NODE_ENV="production";
  fi
- npm run build
- npm run deploy
- [ "$TRAVIS_BRANCH" == "develop" ] && rsync -a -e "ssh -i deploy-keys/draft" build/ $SCP_USERNAME@$SCP_HOST:
branches:
  only:
  - develop
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3a54c86f385b_key -iv $encrypted_3a54c86f385b_iv
  -in draft.enc -out draft -d
